"""Add Risk_Category to User

Revision ID: 27515d6d793f
Revises: 322012404051
Create Date: 2025-07-20 20:50:33.322213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27515d6d793f'
down_revision: Union[str, None] = '322012404051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Risk_Category', sa.Enum('HIGH', 'LOW', name='risk_category'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'Risk_Category')
    # ### end Alembic commands ###
