"""2

Revision ID: 322012404051
Revises: bad63e019863
Create Date: 2025-07-20 20:27:01.960029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '322012404051'
down_revision: Union[str, None] = 'bad63e019863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Probability', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('Risk_Category', sa.Enum('High', 'Low', name='risk_category'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'Risk_Category')
    op.drop_column('users', 'Probability')
    # ### end Alembic commands ###
