"""Initial revision

Revision ID: bad63e019863
Revises: 
Create Date: 2025-07-20 16:54:58.243692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad63e019863'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Amt', sa.Float(), nullable=False),
    sa.Column('Trm', sa.Integer(), nullable=False),
    sa.Column('YngAcntAge', sa.Float(), nullable=True),
    sa.Column('CntActv', sa.Integer(), nullable=True),
    sa.Column('CntCls12', sa.Integer(), nullable=True),
    sa.Column('CntOpn12', sa.Integer(), nullable=True),
    sa.Column('CntSttl', sa.Integer(), nullable=True),
    sa.Column('AvgAcntAge', sa.Float(), nullable=True),
    sa.Column('OutBal', sa.Float(), nullable=True),
    sa.Column('OutBalNoMtg', sa.Float(), nullable=True),
    sa.Column('WorstPayStat', sa.Integer(), nullable=True),
    sa.Column('EmpPT', sa.Enum('FULL_TIME', 'PART_TIME', 'SELF_EMPLOYED', 'RETIRED', name='jobtype'), nullable=False),
    sa.Column('EmpRtrd', sa.Integer(), nullable=True),
    sa.Column('EmpSelf', sa.Integer(), nullable=True),
    sa.Column('LoanPurpose', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
